name: ansible_deploy_users

on:
  push:
    branches: [ "main" ]
    
env:
  # Use the same ssh-agent socket value across all jobs
  # Useful when a GH action is using SSH behind-the-scenes
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

  runs-on: ubuntu-latest

  steps:
  - name: Checkout repository
    uses: actions/checkout@v2
    
  # Start ssh-agent but set it to use the same ssh_auth_sock value.
  # The agent will be running in all steps after this, so it
  # should be one of the first.
  - name: Setup SSH passphrase
    env:
      SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE}}
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
    run: |
      ssh-agent -a $SSH_AUTH_SOCK > /dev/null
      echo 'echo $SSH_PASSPHRASE' > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
      echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null

  # Debug print out the added identities. This will prove SSH_AUTH_SOCK
  # is persisted across job steps
  - name: Print ssh-add identities
    runs: ssh-add -l

  - name: Run playbook
    uses: dawidd6/action-ansible-playbook@v2
    with:
      # Required, playbook filepath
      playbook: playbook.yml
      # Optional, directory where playbooks live
      directory: ./
      # Optional, SSH private key
      key: ${{secrets.SSH_PRIVATE_KEY}}
      # Optional, literal inventory file contents
      # inventory: |
      #   [all]
      #   example.com

      #   [group1]
      #   example.com
      # Optional, SSH known hosts file content
      known_hosts: .known_hosts
      # Optional, encrypted vault password
      vault_password: ${{secrets.VAULT_PASSWORD}}
      # Optional, galaxy requirements filepath
      requirements: galaxy-requirements.yml
      # Optional, additional flags to pass to ansible-playbook
      options: |
        --inventory .hosts
        --check
        # --limit group1
        # --extra-vars hello=there
        # --verbose
  